### PR TITLE
Ocaml Cordova Notif Android

### PR DESCRIPTION
**Pull request by pbriand**
Add createChannel, deleteChannel & listChannel to mli (cf phonegap)

depends of ocsigen-start and bs

### CODE REVIEW

**Comment by jrochel** [comment]
@dannywillems: bump

**Comment by dannywillems** [comment]
Seems ok for me. Merging it. I will update soon on opam by using the version tag 1.1.2 @pbriand @jrochel

**Comment by dannywillems** [comment]
Sorry, changing my mind. Seems `listChannels` is expecting a JSONArray in its callback, not unit. https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationlistchannelssuccesshandler

EDIT:
The correct signature is:
```ocaml
val list_channels :
  success:(Channel_properties.t list -> unit)  ->
  unit
[@@js.global "PushNotification.listChannels"]
```

**Comment by pbriand** [comment]
My bad, I push a new version with the correct signature.

**Pull request merged**
